/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import Connection.ConnectionFactory;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import Connection.ServicoCidade;
import Connection.ServicoConexoes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
/**
 *
 * @author 55119
 */
public class Principal extends javax.swing.JFrame{
    String myDriver = "com.mysql.cj.jdbc.Driver";
    String myUrl = "jdbc:mysql://localhost:3306/MAPA?useUnicode=true&characterEncoding=utf-8";
    int clicks = 0;
    int x_old = 0;
    int y_old=0;
    int x_now = 0;
    int y_now = 0;
    ConnectionFactory conn;
    
    boolean allow_add_points = false;
    Graphics universal_graph;
    ArrayList<Line2D.Float> lines = new ArrayList();
    
    
    /**
     * Creates new form Principal
     */
    public Principal() throws Exception {
        setSize(800,800);
        conn = new ConnectionFactory();
        ServicoCidade sc = new ServicoCidade(this.conn);
        initComponents();
        initComponents2();
        initPopulation();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMap = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();
        AdicionarPontos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ComboCitys = new javax.swing.JComboBox<>();
        ButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ButtonAdd = new javax.swing.JButton();
        SuperiorMenu = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo");
        setBackground(new java.awt.Color(127, 127, 127));
        setMinimumSize(new java.awt.Dimension(900, 934));
        setPreferredSize(new java.awt.Dimension(900, 934));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelMap.setBackground(new java.awt.Color(51, 51, 51));
        PanelMap.setLayout(null);

        Title1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Mapa Interativo:");
        PanelMap.add(Title1);
        Title1.setBounds(0, 10, 190, 19);

        Map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/mapa_esse.png"))); // NOI18N
        Map.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Map.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                MapMouseWheelMoved(evt);
            }
        });
        Map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MapMouseClicked(evt);
            }
        });
        Map.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MapKeyPressed(evt);
            }
        });
        PanelMap.add(Map);
        Map.setBounds(0, 40, 900, 1200);

        getContentPane().add(PanelMap);
        PanelMap.setBounds(0, 0, 900, 860);

        AdicionarPontos.setBackground(new java.awt.Color(51, 51, 51));
        AdicionarPontos.setEnabled(false);
        AdicionarPontos.setMinimumSize(new java.awt.Dimension(900, 934));
        AdicionarPontos.setPreferredSize(new java.awt.Dimension(900, 934));
        AdicionarPontos.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sigla");
        AdicionarPontos.add(jLabel2);
        jLabel2.setBounds(190, 330, 60, 22);

        ComboCitys.setBackground(new java.awt.Color(51, 51, 51));
        ComboCitys.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboCitys.setForeground(new java.awt.Color(255, 255, 255));
        ComboCitys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCitysActionPerformed(evt);
            }
        });
        AdicionarPontos.add(ComboCitys);
        ComboCitys.setBounds(190, 280, 510, 40);

        ButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setText("Cancelar");
        ButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCancelMouseClicked(evt);
            }
        });
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });
        AdicionarPontos.add(ButtonCancel);
        ButtonCancel.setBounds(450, 430, 250, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cidade");
        AdicionarPontos.add(jLabel3);
        jLabel3.setBounds(190, 250, 60, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        AdicionarPontos.add(jTextField1);
        jTextField1.setBounds(190, 360, 510, 40);

        ButtonAdd.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAdd.setText("Adicionar");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });
        AdicionarPontos.add(ButtonAdd);
        ButtonAdd.setBounds(190, 430, 250, 40);

        getContentPane().add(AdicionarPontos);
        AdicionarPontos.setBounds(0, -50, 900, 890);
        AdicionarPontos.setVisible(false);

        SuperiorMenu.setBackground(new java.awt.Color(51, 51, 51));
        SuperiorMenu.setBorder(null);
        SuperiorMenu.setForeground(new java.awt.Color(255, 255, 255));
        SuperiorMenu.setPreferredSize(new java.awt.Dimension(66, 45));

        jMenu5.setBackground(new java.awt.Color(51, 51, 51));
        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Pontos");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Adicionar Ponto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Remover Ponto");
        jMenu5.add(jMenuItem2);

        SuperiorMenu.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(51, 51, 51));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Enlaces");
        SuperiorMenu.add(jMenu6);

        setJMenuBar(SuperiorMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents2(){
        universal_graph =  Map.getGraphics();
        //Map.setLocation(-100,0); // NOI18N
    }
    
    private void initPopulation() throws Exception{
        String query = "select * from cidades";

        ResultSet rs = this.conn.buscar(query);
        while (rs.next()) {
          String nome_cidade = rs.getString("nome_cidade");
          int cordenada_x = rs.getInt("cordenada_x");
          int cordenada_y = rs.getInt("cordenada_y");
          add_point(nome_cidade, cordenada_x, cordenada_y);
          //names_citys_around.add(nome);
        }
        Map.repaint();
        Map.paintComponents(universal_graph);
    }    
    
    private void reset_graph(){
        universal_graph = Map.getGraphics();
        Map.paint(Map.getGraphics());
    }
    
    private Graphics get_graph(){
        return Map.getGraphics();
    }
    
    private void set_click(){
        this.clicks +=1;
    }
    
    private ArrayList<String> search_city(int x, int y) throws Exception{
        System.out.println(x + "," + y);
        ArrayList<String>  names_city = new ArrayList();
        double latitude = 5.48155495 + (y*-0.04885256);
        double longitude = -74.28821548 + (x*0.04895532);
        try {
            names_city = viewTable(latitude, longitude);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

        return names_city;
    }
    
    private void add_line_aresta(int x, int y){
        //Função: Adicionar linha de aresta
        if(this.clicks == 1){
            this.x_old = x;
            this.y_old = y;
        }

        if(this.clicks == 2){
            //((Graphics2D)universal_graph).setRenderingHint(RenderingHints.KEY_ANTIALIASING,  RenderingHints.VALUE_ANTIALIAS_ON);
            ((Graphics2D)universal_graph).setStroke(new BasicStroke(4));


            Line2D.Float line = new Line2D.Float(this.x_old, this.y_old, x, y);
            this.lines.add(line);
            ((Graphics2D)universal_graph).draw(line);
            this.clicks = 0;
        }
    }

    
    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        add_point(ComboCitys.getSelectedItem().toString(), this.x_now, this.y_now);
        AdicionarPontos.setVisible(false);
        SuperiorMenu.setVisible(true);
        PanelMap.setVisible(true);
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ComboCitysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCitysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCitysActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MapKeyPressed

    }//GEN-LAST:event_MapKeyPressed

    private void MapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MapMouseClicked
        if(this.allow_add_points){
            this.x_now=evt.getX();
            this.y_now=evt.getY();
            this.clicks = 0;
            int limite = 0;
            ArrayList<String> names_city = new ArrayList();
            try {
                names_city = search_city(this.x_now, this.y_now);
                //Adicionar_Pontos_1 adc_pontos = ;
                //adc_pontos.setVisible(true);
                //this.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(names_city.size() > 10){limite = 10;}
            else{limite = names_city.size();}

            ComboCitys.removeAllItems();
            for (int i=0;i<limite;i++){
                ComboCitys.addItem(names_city.get(i));
            }

            AdicionarPontos.setVisible(true);
            SuperiorMenu.setVisible(false);
            PanelMap.setVisible(false);

        }

        //add_point(adc_pontos.return_city(), x, y);

        //search_city(this.Map.getGraphics(),evt);
    }//GEN-LAST:event_MapMouseClicked

    private void MapMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_MapMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MapMouseWheelMoved

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.allow_add_points = true;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCancelMouseClicked
        AdicionarPontos.setVisible(false);
        SuperiorMenu.setVisible(true);
        PanelMap.setVisible(true);
    }//GEN-LAST:event_ButtonCancelMouseClicked

    void add_point(String name_city, int x, int y){
        Point point = new Point(name_city, x, y);
    }
    
    public ArrayList<String> viewTable(double latitude , double longitude) throws Exception {
    ArrayList<String> names_citys_around = new ArrayList();    
    
    double compare = 1.5;
    double latitude_max = latitude + compare;
    double latitude_min = latitude - compare;
    double longitude_max = longitude + compare;
    double longitude_min = longitude - compare;
    
    
    double diff_longitude_menor = 100000;
    double diff_latitude_menor = 100000;
    String nome_definitivo = "";
    
    String query = "select * from municipios WHERE latitude BETWEEN " + latitude_min + " and " + latitude_max + "" + " and " +
            "longitude BETWEEN " + longitude_min + " and " + longitude_max + "";
    
    ResultSet rs = this.conn.buscar(query);
    while (rs.next()) {
      String nome = rs.getString("nome");
      names_citys_around.add(nome);
    }
    return names_citys_around;
  }
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // create our mysql database connection
        //</editor-fold>

        // create our mysql database connection
        
        
        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Principal().setVisible(true);
                    
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    class Point{
        static final long serialVersionUID = 1;
        private int coordinates_x = 0;
        private int coordinates_y = 0;
        private String name = "";
        private javax.swing.JPanel princ;
        
        Point(String name_city, int x, int y){
            if(name_city != ""){
                princ = new javax.swing.JPanel();
                int tam_img = 20;
                this.coordinates_x = x;
                this.coordinates_y = y;
                this.name = name_city;
                princ.setLayout(null);
                princ.setBackground(Color.BLUE);
                //this.setPreferredSize(new Dimension(30, 30));
                //this.setMinimumSize(new Dimension(30, 30));
                princ.setBounds(x-tam_img/2, y-tam_img/2, tam_img, tam_img);
                princ.setVisible(true);
                princ.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        System.out.println(name);
                        set_click();
                        add_line_aresta(x, y);
                        princ.setVisible(false);
                        princ.setVisible(true);
                    }
                });
            }
            
            Map.add(princ);
            System.out.println("Added");
            Map.paintComponents(universal_graph);
        }
        
        
        public int getX(){
         return this.coordinates_x;
        }
        
        public int getY(){
         return this.coordinates_y;
        }
        
        public String getName(){
         return this.name;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdicionarPontos;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JComboBox<String> ComboCitys;
    private javax.swing.JLabel Map;
    private javax.swing.JPanel PanelMap;
    private javax.swing.JMenuBar SuperiorMenu;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
